### ISSUE TITLE
[Help] 从源码构建的镜像，用户登录后提示 "服务器出错啦！(500, undefined))"

### ISSUE THREAD

**Issue by wyzhh** [PKUHPC/SCOW#1301]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [x] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

从github中拉取了v1.5.2版本scow，随后使用docker build构建成功了镜像。从本地启动后可以使用ldap验证用户登录，用户登录后提示 "服务器出错啦！(500, undefined))"。检查log文件后发现portal-web中记录了报错信息，如下
"   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000

Read dir config clusters of id msdw from /etc/scow/clusters/msdw.yaml
TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCapabilities (/app/libs/auth/build/getCapabilities.js:24:19)
    at async queryCapabilities (/app/apps/portal-web/config.js:39:12)
    at async buildRuntimeConfig (/app/apps/portal-web/config.js:168:24)
    at async module.exports (/app/apps/portal-web/next.config.js:32:25)
    at async normalizeConfig (/app/node_modules/.pnpm/next@14.1.4_patch_hash=7ao6rxevvndlxe5cfehmimnule_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config-shared.js:150:12)
    at async loadConfig (/app/node_modules/.pnpm/next@14.1.4_patch_hash=7ao6rxevvndlxe5cfehmimnule_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config.js:712:28)
    at async initialize (/app/node_modules/.pnpm/next@14.1.4_patch_hash=7ao6rxevvndlxe5cfehmimnule_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:55:20)
    at async Server.<anonymous> (/app/node_modules/.pnpm/next@14.1.4_patch_hash=7ao6rxevvndlxe5cfehmimnule_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:247:>
  [cause]: Error: connect ECONNREFUSED 172.25.0.5:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.25.0.5',
    port: 5000
  }
}"

### 期望结果 | What did you expect to happen

请问这是哪个服务的问题？我应该从哪个下手解决？

### 之前运行正常吗？ | Did this work before?

尝试使用cli启动v1.5.2是可以正常运行的，但构建scow v1.5.2 docker镜像，用户登录后提示 "服务器出错啦！(500, undefined))"

### 复现方法 | Steps To Reproduce

git clone https://github.com/PKUHPC/SCOW --depth=1 --branch v1.5.2
docker build -f docker/Dockerfile.scow -t scow:latest .
docker  compose -f docker-compose.yml up -d

### 运行环境 | Environment

```Markdown
- OS: Rocky Linux 8.9
- Scheduler: slurm 22.05.8
- Docker: 26.1.3
- Docker-compose: v2.27.0
- SCOW cli:
- SCOW: v1.5.2
- Adapter: 1.5.0
```

### 备注 | Anything else?

无

**Comment by wyzhh** [comment]
问题解决了，可能是网络问题，第一次构建的镜像有问题。重新构建后就可以了
