### ISSUE TITLE
deploy the example mis cant init (500 error)

### ISSUE THREAD

**Issue by lixeon** [PKUHPC/SCOW#799]
The install and step whole follow the https://pkuhpc.github.io/SCOW/docs/deploy/get-started/vagrant.

vagrant ssh scow
docker ps -a

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS                          PORTS                                                                                                    NAMES
70bc32e6113e   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Up 8 minutes                    80/tcp, 3000/tcp, 5000/tcp                                                                               scow-deployment-portal-server-1
b933deb912f8   ghcr.io/pkuhpc/novnc-client-docker:master    "/docker-entrypoint.…"   8 minutes ago   Up 8 minutes                    80/tcp                                                                                                   scow-deployment-novnc-1
3f9e82ba83c8   redis:alpine                                 "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes                    6379/tcp                                                                                                 scow-deployment-redis-1
ea4f129c4f07   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Restarting (1) 35 seconds ago                                                                                                            scow-deployment-mis-server-1
91d317676351   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Up 8 minutes                    80/tcp, 3000/tcp, 5000/tcp                                                                               scow-deployment-auth-1
dec858126610   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Up 8 minutes                    80/tcp, 3000/tcp, 5000/tcp                                                                               scow-deployment-mis-web-1
e467378cdb21   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Up 8 minutes                    3000/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 5000/tcp                                                    scow-deployment-gateway-1
0c46cf16f72d   mirrors.pku.edu.cn/pkuhpc/scow/scow:master   "./entrypoint.sh"        8 minutes ago   Up 8 minutes                    80/tcp, 3000/tcp, 5000/tcp                                                                               scow-deployment-portal-web-1
5831135f3932   mysql:8                                      "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes                    3306/tcp, 33060/tcp                                                                                      scow-deployment-db-1
57a345641701   fluentd:v1.14.0-1.0                          "tini -- /bin/entryp…"   8 minutes ago   Up 8 minutes                    5140/tcp, 0.0.0.0:24224->24224/tcp, 0.0.0.0:24224->24224/udp, :::24224->24224/tcp, :::24224->24224/udp   scow-deployment-log-1
```

./cli compose logs -f mis-server

```
scow-deployment-mis-server-1  | > @scow/mis-server@0.8.1 serve
scow-deployment-mis-server-1  | > node build/index.js
scow-deployment-mis-server-1  | 
scow-deployment-mis-server-1  | {"level":30,"time":1691906765556,"pid":18,"hostname":"ea4f129c4f07","msg":"Hook disabled"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906767473,"pid":18,"hostname":"ea4f129c4f07","version":{"commit":"f9fbd4cd21154fdb4024066013da2200feb64c49"},"msg":"@scow/mis-server: "}
scow-deployment-mis-server-1  | {"level":40,"time":1691906765652,"pid":18,"hostname":"ea4f129c4f07","msg":"createUser.userIdPattern is deprecated, please use createUser.builtin.userIdPattern"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906767473,"pid":18,"hostname":"ea4f129c4f07","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906768171,"pid":18,"hostname":"ea4f129c4f07","msg":"Checking if root can login to hpc01 by login node login"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906768272,"pid":18,"hostname":"ea4f129c4f07","msg":"Root can login to hpc01 by login node login"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906768291,"pid":18,"hostname":"ea4f129c4f07","plugin":"price","msg":"Default Price Map: {}"}
scow-deployment-mis-server-1  | {"level":30,"time":1691906768291,"pid":18,"hostname":"ea4f129c4f07","plugin":"price","msg":"Tenant specific prices {}"}
scow-deployment-mis-server-1  | {"level":50,"time":1691906768309,"pid":18,"hostname":"ea4f129c4f07","plugin":"price","err":{"type":"Error","message":"14 UNAVAILABLE: No connection established","stack":"Error: 14 UNAVAILABLE: No connection established\n    at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:192:76)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:160:32)\n    at ServiceClientImpl.getClusterConfig (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:18:13\n    at new Promise (<anonymous>)\n    at asyncClientCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:15:12)\n    at /app/apps/mis-server/build/bl/PriceMap.js:47:117\n    at /app/apps/mis-server/build/plugins/clusters.js:63:24\n    at Array.map (<anonymous>)\n    at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:62:18)\n    at createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:47:39)","code":14,"details":"No connection established","metadata":{}},"msg":"Executing on hpc01 failed"}
scow-deployment-mis-server-1  | {"level":50,"time":1691906768309,"pid":18,"hostname":"ea4f129c4f07","plugin":"price","msg":"Cluster ops fails at clusters [{\"cluster\":\"hpc01\",\"error\":{\"code\":14,\"details\":\"No connection established\",\"metadata\":{}}}]"}
scow-deployment-mis-server-1  | /app/apps/mis-server/build/plugins/clusters.js:81
scow-deployment-mis-server-1  |                 throw new tsgrpc_common_1.ServiceError({
scow-deployment-mis-server-1  |                       ^
scow-deployment-mis-server-1  | 
scow-deployment-mis-server-1  | ServiceError
scow-deployment-mis-server-1  |     at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:81:23)
scow-deployment-mis-server-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
scow-deployment-mis-server-1  |     at async createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:47:19)
scow-deployment-mis-server-1  |     at async /app/apps/mis-server/build/plugins/price.js:20:22
scow-deployment-mis-server-1  |     at async Server.register (/app/node_modules/.pnpm/@ddadaal+tsgrpc-server@0.19.4_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-server/lib/server.js:117:9)
scow-deployment-mis-server-1  |     at async createServer (/app/apps/mis-server/build/app.js:41:9)
scow-deployment-mis-server-1  |     at async main (/app/apps/mis-server/build/index.js:19:20) {
scow-deployment-mis-server-1  |   code: 13,
scow-deployment-mis-server-1  |   details: 'hpc01',
scow-deployment-mis-server-1  |   metadata: Metadata {
scow-deployment-mis-server-1  |     internalRepr: Map(2) {
scow-deployment-mis-server-1  |       'is_scow_error' => [ '1' ],
scow-deployment-mis-server-1  |       'scow_error_code' => [ 'CLUSTEROPS_ERROR' ]
scow-deployment-mis-server-1  |     },
scow-deployment-mis-server-1  |     options: {}
scow-deployment-mis-server-1  |   }
scow-deployment-mis-server-1  | }
scow-deployment-mis-server-1  | 
scow-deployment-mis-server-1  | Node.js v18.17.0
scow-deployment-mis-server-1 exited with code 1
```

It seems cant connect the db. 

And the mis.yaml is that 
```

# 管理系统数据库的信息。可以不修改
db:
  host: db
  port: 3306
  user: root
  dbName: scow

# 获取作业相关配置
fetchJobs:
  # 周期性获取数据
  periodicFetch:
    # 是否开启
    enabled: true
    # 周期的cron表达式
    cron: "10 */10 * * * *"

# 预定义的充值类型
predefinedChargingTypes:
  - 测试

# 账户名的规则
accountNamePattern:
  # 正则表达式
  regex: "(a_)[a-z]+$"

  # 出错时的消息
  # errorMessage: ""

createUser:
  # 创建用户时，用户ID的规则。不设置就没有限制
  userIdPattern:
    # 正则表达式
    regex: "^[a-zA-Z0-9_]+$"
    # 出错时的消息
    errorMessage: "只能由字母、下划线、数字组成"
```

How to fix it?

**Comment by huangjun0210** [comment]
Log in to the slurm node，check adapter is ok ？
`ps -ef |grep scow-slurm-adapter-amd64 `
if not 
`nohup /adapter/scow-slurm-adapter-amd64 > /adapter/server.log 2>&1 &`

**Comment by vanstriker** [comment]
no more response. close issue
