### ISSUE TITLE
shell卡顿ldap

### ISSUE THREAD

**Issue by xuetong520** [PKUHPC/SCOW#834]
[io] [user] Error occurred from server. Disconnect. [
  Error: 13 INTERNAL: Error when connecting to remote
      at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:419:73)
      at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
      at /app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
  for call at
      at ServiceClientImpl.makeBidiStreamRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:403:32)
      at ServiceClientImpl.shell (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
      at asyncDuplexStreamCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-client/lib/duplexStream.js:15:11)
      at WebSocketServer.<anonymous> (/app/apps/portal-web/.next/server/chunks/5288.js:801:97)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 13,
    details: 'Error when connecting to remote',
    metadata: Metadata { internalRepr: [Map], options: {} }
  }
]

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
