### ISSUE TITLE
部署SCOW看不到登录URL

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#909]
安装SCOW后，都不知道从什么URL登录，运行./cli compose up -d启动门户系统。通过IP地址登录后，显示404，官方的文档能不能把配置的和登录的URL写的更清楚点。
![image](https://github.com/PKUHPC/SCOW/assets/6166167/fe4f215f-f9d3-40b1-8c55-881b5bb7bc18)

**Comment by zhengkang2020** [comment]
部署scow的这台机器的域名或者IP/init 

比如mis在install.yaml部署路径是/mis，scow ip是192.168.1.100，域名设置的是hpc.xxx.com ，刚安装好未初始化可以通过192.168.1.100/mis/init 或hpc.xxx.com/mis/init 先初始化[参考链接](https://pkuhpc.github.io/SCOW/docs/deploy/config/mis/init)
初始化之后会自动跳转到门户系统

**Comment by liu-shaobo** [comment]
ip/mis/init或ip/init都显示 404
`2023/10/24 09:01:15 [error] 29#29: *6 mis-web could not be resolved (3: Host not found), client: 106.75.220.2, server: , request: "GET /mis/init HTTP/1.1", host: "106.75.246.247"
2023/10/24 09:01:15 [error] 29#29: *6 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 106.75.220.2, server: , request: "GET /mis/init HTTP/1.1", host: "106.75.246.247"
106.75.220.2 - - [24/Oct/2023:09:01:15 +0000] "GET /mis/init HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"`

`2023/10/24 09:01:57 [error] 29#29: *6 portal-web could not be resolved (3: Host not found), client: 106.75.220.2, server: , request: "GET /init HTTP/1.1", host: "106.75.246.247"
2023/10/24 09:01:57 [error] 29#29: *6 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 106.75.220.2, server: , request: "GET /init HTTP/1.1", host: "106.75.246.247"
106.75.220.2 - - [24/Oct/2023:09:01:57 +0000] "GET /init HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
2023/10/24 09:01:57 [error] 29#29: *6 portal-web could not be resolved (3: Host not found), client: 106.75.220.2, server: , request: "GET /init HTTP/1.1", host: "106.75.246.247"
2023/10/24 09:01:57 [error] 29#29: *6 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 106.75.220.2, server: , request: "GET /init HTTP/1.1", host: "106.75.246.247"
106.75.220.2 - - [24/Oct/2023:09:01:57 +0000] "GET /init HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
`

**Comment by zhengkang2020** [comment]
- 看下这个
```shell
cd /scow
./cli compose ps
 ```

- 看下config/clusters/hpc01.yaml

- auth.yaml
```shell
authType: ldap
ldap:
  url: ldap://10.23.15.181
  bindDN: "cn=Manager,ou={ou},o={dn}"
  bindPassword: "456qwe"
searchBase: ""
  userFilter: "(uid=*)"
attrs:
  uid: uid
addUser:
  userBase: "ou=People,ou={ou},o={dn}"
  homeDir: /gfs/home/{{ userId }}
  groupStrategy: newGroupPerUser
  newGroupPerUser:
    groupBase: "ou=Group,ou={ou},o={dn}"
  oneGroupForAllUsers:
    gidNumber: 5000
```
这里的{ou}, {dn} 填provider.sh脚本里具体的内容，可以用phpldapadmin连接测试

**Comment by liu-shaobo** [comment]
修改了auth.yaml和hpc01.yaml文件，错误如下
```
INFO: Loaded plugins: []
NAME                   IMAGE                                         COMMAND                                          SERVICE         CREATED          STATUS                                  PORTS
scow-audit-db-1        mysql:8                                       "docker-entrypoint.sh mysqld"                    audit-db        21 seconds ago   Up 19 seconds                           3306/tcp, 33060/tcp
scow-audit-server-1    mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                audit-server    21 seconds ago   Up 15 seconds                           80/tcp, 3000/tcp, 5000/tcp
scow-auth-1            mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                auth            21 seconds ago   Restarting (1) 2 seconds ago
scow-db-1              mysql:8                                       "docker-entrypoint.sh mysqld"                    db              21 seconds ago   Up 19 seconds                           3306/tcp, 33060/tcp
scow-gateway-1         mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                gateway         21 seconds ago   Up 20 seconds                           3000/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 5000/tcp
scow-log-1             fluentd:v1.14.0-1.0                           "tini -- /bin/entrypoint.sh fluentd"             log             21 seconds ago   Up 20 seconds                           5140/tcp, 0.0.0.0:24224->24224/tcp, 0.0.0.0:24224->24224/udp, :::24224->24224/tcp, :::24224->24224/udp
scow-mis-server-1      mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                mis-server      21 seconds ago   Up 2 seconds                            80/tcp, 3000/tcp, 5000/tcp
scow-mis-web-1         mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                mis-web         21 seconds ago   Restarting (1) 1 second ago
scow-novnc-1           ghcr.io/pkuhpc/novnc-client-docker:master     "/docker-entrypoint.sh nginx -g 'daemon off;'"   novnc           21 seconds ago   Up 19 seconds                           80/tcp
scow-portal-server-1   mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                portal-server   21 seconds ago   Up 19 seconds                           80/tcp, 3000/tcp, 5000/tcp
scow-portal-web-1      mirrors.pku.edu.cn/pkuhpc-icode/scow:v1.0.0   "./entrypoint.sh"                                portal-web      21 seconds ago   Restarting (1) Less than a second ago
scow-redis-1           redis:alpine                                  "docker-entrypoint.sh redis-server"              redis           21 seconds ago   Up 20 seconds                           6379/tcp
```

```
> @scow/mis-server@1.0.0 serve
> node build/index.js

{"level":30,"time":1698141935524,"pid":18,"hostname":"e657ddbb4aab","msg":"Hook disabled"}
{"level":30,"time":1698141936888,"pid":18,"hostname":"e657ddbb4aab","version":{"tag":"v1.0.0","commit":"663a4ec9decded010cb588401a1773cb11df3fcb"},"msg":"@scow/mis-server: "}
{"level":30,"time":1698141936889,"pid":18,"hostname":"e657ddbb4aab","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packets/packet.js:728
    const err = new Error(message);
                ^

Error: Access denied for user 'root'@'172.21.0.4' (using password: YES)
    at Packet.asError (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'root'@'172.21.0.4' (using password: YES)",
  sql: undefined
}

Node.js v18.17.1
```

* hpc01.yaml
```
displayName: hpc01

# 指定slurm配置
loginNodes:
  # 登录节点展示名称
  - name: node001
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: node001

# 适配器地址(ip地址:端口号)
adapterUrl: 10.23.15.181:8999

# 门户系统代理网关节点配置
# proxyGateway:
#   # 带协议，不要以/结尾
#   url: http://10.2.3.2:1080

#   # 是否在这个机器上自动配置nginx
#   autoSetupNginx: true
```

* auth.yml
```
authType: ldap
ldap:
  url: ldap://10.23.15.181
  bindDN: "cn=Manager,ou=example,o=com"
  bindPassword: "123456"
searchBase: ""
  userFilter: "(uid=*)"
attrs:
  uid: uid
addUser:
  userBase: "ou=People,ou=example,o=com"
  homeDir: /gfs/home/{{ userId }}
  groupStrategy: newGroupPerUser
  newGroupPerUser:
    groupBase: "ou=Group,ou=example,o=com"
  oneGroupForAllUsers:
    gidNumber: 5000
```

**Comment by liu-shaobo** [comment]
mis-server容器错误日志
```
> @scow/mis-server@1.0.0 serve
> node build/index.js

{"level":30,"time":1698225843318,"pid":18,"hostname":"7b6f5d4c2b68","msg":"Hook disabled"}
{"level":30,"time":1698225844959,"pid":18,"hostname":"7b6f5d4c2b68","version":{"tag":"v1.0.0","commit":"663a4ec9decded010cb588401a1773cb11df3fcb"},"msg":"@scow/mis-server: "}
{"level":30,"time":1698225844960,"pid":18,"hostname":"7b6f5d4c2b68","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 172.25.0.9:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.25.0.9',
  port: 3306,
  fatal: true
}

Node.js v18.17.1

> @scow/mis-server@1.0.0 serve
> node build/index.js

{"level":30,"time":1698225863263,"pid":18,"hostname":"7b6f5d4c2b68","msg":"Hook disabled"}
{"level":30,"time":1698225864743,"pid":18,"hostname":"7b6f5d4c2b68","version":{"tag":"v1.0.0","commit":"663a4ec9decded010cb588401a1773cb11df3fcb"},"msg":"@scow/mis-server: "}
{"level":30,"time":1698225864743,"pid":18,"hostname":"7b6f5d4c2b68","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DB_PASSWORD":"must!chang3this"},"msg":"Loaded env config"}
{"level":30,"time":1698225865291,"pid":18,"hostname":"7b6f5d4c2b68","msg":"Checking if root can login to hpc01 by login node node001"}
{"level":30,"time":1698225865324,"pid":18,"hostname":"7b6f5d4c2b68","msg":"Root can login to hpc01 by login node node001"}
{"level":30,"time":1698225865338,"pid":18,"hostname":"7b6f5d4c2b68","plugin":"price","msg":"Default Price Map: {}"}
{"level":30,"time":1698225865338,"pid":18,"hostname":"7b6f5d4c2b68","plugin":"price","msg":"Tenant specific prices {}"}
{"level":50,"time":1698225865362,"pid":18,"hostname":"7b6f5d4c2b68","plugin":"price","err":{"type":"Error","message":"13 INTERNAL: Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)","stack":"Error: 13 INTERNAL: Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n    at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:192:76)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/client.js:160:32)\n    at ServiceClientImpl.getClusterConfig (/app/node_modules/.pnpm/@grpc+grpc-js@1.8.21/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:18:13\n    at new Promise (<anonymous>)\n    at asyncClientCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:15:12)\n    at /app/apps/mis-server/build/bl/PriceMap.js:49:117\n    at /app/apps/mis-server/build/plugins/clusters.js:63:24\n    at Array.map (<anonymous>)\n    at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:62:18)\n    at createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:49:39)","code":13,"details":"Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)","metadata":{"content-type":["application/grpc"],"grpc-status-details-bin":[{"type":"Buffer","data":[8,13,18,83,69,114,114,111,114,32,49,48,52,53,32,40,50,56,48,48,48,41,58,32,65,99,99,101,115,115,32,100,101,110,105,101,100,32,102,111,114,32,117,115,101,114,32,39,114,111,111,116,39,64,39,108,111,99,97,108,104,111,115,116,39,32,40,117,115,105,110,103,32,112,97,115,115,119,111,114,100,58,32,89,69,83,41,26,62,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,18,10,16,83,81,76,95,81,85,69,82,89,95,70,65,73,76,69,68]}]}},"msg":"Executing on hpc01 failed"}
{"level":50,"time":1698225865362,"pid":18,"hostname":"7b6f5d4c2b68","plugin":"price","msg":"Cluster ops fails at clusters [{\"cluster\":\"hpc01\",\"error\":{\"code\":13,\"details\":\"Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\",\"metadata\":{\"content-type\":[\"application/grpc\"],\"grpc-status-details-bin\":[{\"type\":\"Buffer\",\"data\":[8,13,18,83,69,114,114,111,114,32,49,48,52,53,32,40,50,56,48,48,48,41,58,32,65,99,99,101,115,115,32,100,101,110,105,101,100,32,102,111,114,32,117,115,101,114,32,39,114,111,111,116,39,64,39,108,111,99,97,108,104,111,115,116,39,32,40,117,115,105,110,103,32,112,97,115,115,119,111,114,100,58,32,89,69,83,41,26,62,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,18,10,16,83,81,76,95,81,85,69,82,89,95,70,65,73,76,69,68]}]}}}]"}
/app/apps/mis-server/build/plugins/clusters.js:82
                throw new tsgrpc_common_1.ServiceError({
                      ^

ServiceError
    at Object.callOnAll (/app/apps/mis-server/build/plugins/clusters.js:82:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createPriceMap (/app/apps/mis-server/build/bl/PriceMap.js:49:19)
    at async /app/apps/mis-server/build/plugins/price.js:20:22
    at async Server.register (/app/node_modules/.pnpm/@ddadaal+tsgrpc-server@0.19.4_@grpc+grpc-js@1.8.21/node_modules/@ddadaal/tsgrpc-server/lib/server.js:117:9)
    at async createServer (/app/apps/mis-server/build/app.js:41:9)
    at async main (/app/apps/mis-server/build/index.js:19:20) {
  code: 13,
  details: "hpc01: Error: 13 INTERNAL: Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)",
  metadata: Metadata {
    internalRepr: Map(2) {
      'is_scow_error' => [ '1' ],
      'scow_error_code' => [ 'CLUSTEROPS_ERROR' ]
    },
    options: {}
  }
}

Node.js v18.17.1
