### ISSUE TITLE
创建初始管理员用户错误

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#912]
![image](https://github.com/PKUHPC/SCOW/assets/6166167/3b5174bd-0b3b-4b31-98d6-b06ee4626dae)

![image](https://github.com/PKUHPC/SCOW/assets/6166167/1497ba5f-9275-40bc-8c55-03aa91168fd1)

* scow-mis-server-1错误如下：
```
{"level":30,"time":1698228387574,"pid":18,"hostname":"35b9facdb3a5","req":"2r","path":"/scow.server.InitService/UserExists","msg":"Starting request"}
{"level":30,"time":1698228387591,"pid":18,"hostname":"35b9facdb3a5","req":"2r","path":"/scow.server.InitService/UserExists","msg":"Request completed."}
{"level":30,"time":1698228389129,"pid":18,"hostname":"35b9facdb3a5","req":"2s","path":"/scow.server.InitService/QuerySystemInitialized","msg":"Starting request"}
{"level":30,"time":1698228389132,"pid":18,"hostname":"35b9facdb3a5","req":"2s","path":"/scow.server.InitService/QuerySystemInitialized","msg":"Request completed."}
{"level":30,"time":1698228389135,"pid":18,"hostname":"35b9facdb3a5","req":"2t","path":"/scow.server.InitService/CreateInitAdmin","msg":"Starting request"}
{"level":50,"time":1698228389156,"pid":18,"hostname":"35b9facdb3a5","msg":"HTTP Error when calling auth HTTP API. Status code 500"}
{"level":50,"time":1698228389160,"pid":18,"hostname":"35b9facdb3a5","msg":"Error creating user in auth."}
{"level":50,"time":1698228389160,"pid":18,"hostname":"35b9facdb3a5","req":"2t","path":"/scow.server.InitService/CreateInitAdmin","code":13,"message":"Error creating user 8 in auth.","msg":"Error occurred. Return the error."}
```
* scow-auth-1错误如下：
```
{"level":30,"time":1698291600589,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-c","req":{"method":"GET","url":"/capabilities","hostname":"auth:5000","remoteAddress":"172.26.0.10","remotePort":13370},"msg":"incoming request"}
{"level":30,"time":1698291600590,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-c","res":{"statusCode":200},"responseTime":0.5786390006542206,"msg":"request completed"}
{"level":30,"time":1698291600595,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-d","req":{"method":"GET","url":"/user?identityId=test","hostname":"auth:5000","remoteAddress":"172.26.0.10","remotePort":13370},"msg":"incoming request"}
{"level":30,"time":1698291600600,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-d","msg":"Search started"}
{"level":30,"time":1698291600600,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-d","msg":"Received end event. {\"messageID\":2,\"protocolOp\":101,\"controls\":[],\"log\":{},\"status\":0,\"matchedDN\":\"\",\"errorMessage\":\"\",\"referrals\":[],\"connection\":{\"connecting\":false,\"_hadError\":false,\"_parent\":null,\"_host\":null,\"_closeAfterHandlingError\":false,\"_readableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"buffer\":{\"head\":null,\"tail\":null,\"length\":0},\"length\":0,\"pipes\":[],\"flowing\":true,\"ended\":false,\"endEmitted\":false,\"reading\":false,\"constructed\":true,\"sync\":false,\"needReadable\":true,\"emittedReadable\":false,\"readableListening\":false,\"resumeScheduled\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"destroyed\":false,\"errored\":null,\"closed\":false,\"closeEmitted\":false,\"defaultEncoding\":\"utf8\",\"awaitDrainWriters\":null,\"multiAwaitDrain\":false,\"readingMore\":false,\"dataEmitted\":true,\"decoder\":null,\"encoding\":null},\"_events\":{\"end\":[null,null]},\"_eventsCount\":5,\"_writableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"finalCalled\":false,\"needDrain\":false,\"ending\":false,\"ended\":false,\"finished\":false,\"destroyed\":false,\"decodeStrings\":false,\"defaultEncoding\":\"utf8\",\"length\":0,\"writing\":false,\"corked\":0,\"sync\":false,\"bufferProcessing\":false,\"writecb\":null,\"writelen\":0,\"afterWriteTickInfo\":null,\"buffered\":[],\"bufferedIndex\":0,\"allBuffers\":true,\"allNoop\":true,\"pendingcb\":0,\"constructed\":true,\"prefinished\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"errored\":null,\"closed\":false,\"closeEmitted\":false},\"allowHalfOpen\":false,\"_sockname\":null,\"_pendingData\":null,\"_pendingEncoding\":\"\",\"server\":null,\"_server\":null},\"attributes\":[],\"notAttributes\":[],\"sentEntries\":0}"}
{"level":30,"time":1698291600601,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-d","msg":"Disconnected LDAP connection."}
{"level":30,"time":1698291600602,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-d","res":{"statusCode":404},"responseTime":6.21068799495697,"msg":"request completed"}
{"level":30,"time":1698291601952,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","req":{"method":"POST","url":"/user","hostname":"auth:5000","remoteAddress":"172.26.0.10","remotePort":13370},"msg":"incoming request"}
{"level":30,"time":1698291601956,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","msg":"ldap.addUser.groupStrategy is newGroupPerUser. Creating new group for the user."}
{"level":30,"time":1698291601956,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","msg":"Adding group uid=test,ou=Group,dc=example,dc=com with entry info {\"objectClass\":[\"posixGroup\"],\"memberUid\":\"test\",\"gidNumber\":66018}"}
{"level":30,"time":1698291601958,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","msg":"Disconnected LDAP connection."}
{"level":50,"time":1698291601959,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","req":{"method":"POST","url":"/user","hostname":"auth:5000","remoteAddress":"172.26.0.10","remotePort":13370},"res":{"statusCode":500},"err":{"type":"","message":"object class 'posixGroup' requires attribute 'cn'","stack":"ObjectclassViolationError: object class 'posixGroup' requires attribute 'cn'\n    at messageCallback (/app/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:1220:45)\n    at Parser.onMessage (/app/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:888:14)\n    at Parser.emit (node:events:514:28)\n    at Parser.write (/app/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/messages/parser.js:107:8)\n    at Socket.onData (/app/node_modules/.pnpm/ldapjs@2.3.3/node_modules/ldapjs/lib/client/client.js:875:22)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","lde_message":"object class 'posixGroup' requires attribute 'cn'","lde_dn":null},"msg":"object class 'posixGroup' requires attribute 'cn'"}
{"level":30,"time":1698291601959,"pid":18,"hostname":"f2bda9b5f1b3","reqId":"req-e","res":{"statusCode":500},"responseTime":6.792053997516632,"msg":"request completed"}
```

* config/auth.yml文件配置
```
authType: ldap
ldap:
  url: ldap://10.23.15.181
  bindDN: "cn=Manager,dc=example,dc=com"
  bindPassword: "456qwe"
  searchBase: "dc=example,dc=com"
  userFilter: "(uid=*)"
  attrs:
    uid: uid
    name: cn
    mail: mail
  addUser:
    userBase: "ou=People,dc=example,dc=com"
    homeDir: /gfs/home/{{ userId }}
    groupStrategy: newGroupPerUser
    newGroupPerUser:
      groupBase: "ou=Group,dc=example,dc=com"
    oneGroupForAllUsers:
      gidNumber: 5000

**Comment by liu-shaobo** [comment]
```newGroupPerUser:
增加
  groupIdDnKey: cn
