### ISSUE TITLE
scow通过shell登陆失败

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#967]
CentOS-7.8
SCOW v1.1.0
SCOW节点和SLURM控制节点、计算节点都是同一台机器；服务节点以root用户免密SSH登录；
<img width="458" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/a506c52b-9f12-4c47-bc11-56ec01755e9a">

并且提交作业时提示
无法以用户身份连接到登录节点。请确认您的家目录的权限为700、750或者755
<img width="417" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/02ea47e7-6217-421d-9108-af2ace8b732c">

* portal-web日志
```
[io] [admin] Connection request received. []
[io] [admin] Connected to shell []
Operation Log Server disabled
Attempt to call Log shellLogin with { clusterId: 'hpc001', loginNode: '10.7.2.177' }
[io] [admin] Error occurred from server. Disconnect. [
  Error: 13 INTERNAL: Error when connecting to remote
      at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/client.js:419:73)
      at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
      at /app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
  for call at
      at ServiceClientImpl.makeBidiStreamRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/client.js:403:32)
      at ServiceClientImpl.shell (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.5/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
      at asyncDuplexStreamCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.6_@grpc+grpc-js@1.9.5/node_modules/@ddadaal/tsgrpc-client/lib/duplexStream.js:15:11)
      at WebSocketServer.<anonymous> (/app/apps/portal-web/.next/server/chunks/5288.js:807:97)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 13,
    details: 'Error when connecting to remote',
    metadata: Metadata { internalRepr: [Map], options: {} }
  }
]
```
* portal-server日志
```
{"level":30,"time":1699584266270,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","msg":"Starting request"}
{"level":30,"time":1699584266271,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","shell":{"cluster":"hpc001","loginNode":"10.7.2.177","userId":"admin","cols":80,"rows":24,"path":""},"msg":"Received shell connection"}
{"level":30,"time":1699584266290,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","shell":{"cluster":"hpc001","loginNode":"10.7.2.177","userId":"admin","cols":80,"rows":24,"path":""},"msg":"Login to 10.7.2.177 as admin failed. Try inserting public key"}
{"level":30,"time":1699584266290,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","shell":{"cluster":"hpc001","loginNode":"10.7.2.177","userId":"admin","cols":80,"rows":24,"path":""},"msg":"Adding key to user admin to 10.7.2.177"}
{"level":30,"time":1699584266522,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","shell":{"cluster":"hpc001","loginNode":"10.7.2.177","userId":"admin","cols":80,"rows":24,"path":""},"msg":"/gfs/home/admin/.ssh/authorized_keys exists for user admin in 10.7.2.177. Appending public key"}
{"level":50,"time":1699584266545,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","shell":{"cluster":"hpc001","loginNode":"10.7.2.177","userId":"admin","cols":80,"rows":24,"path":""},"err":{"type":"Error","message":"All configured authentication methods failed","stack":"Error: All configured authentication methods failed\n    at doNextAuth (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/client.js:803:21)\n    at tryNextAuth (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/client.js:993:7)\n    at USERAUTH_FAILURE (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/client.js:373:11)\n    at 51 (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)\n    at Protocol.onPayload (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)\n    at AESGCMDecipherBinding.decrypt (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/protocol/crypto.js:1086:26)\n    at Protocol.parsePacket [as _parse] (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/app/node_modules/.pnpm/ssh2@1.11.0/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:517:28)","level":"client-authentication"},"msg":"Login to 10.7.2.177 as admin still failed after inserting key"}
{"level":50,"time":1699584266545,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","err":{"type":"ServiceError","message":"Error when connecting to remote","stack":"Error: Error when connecting to remote\n    at /app/apps/portal-server/build/utils/ssh.js:75:19\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.shell (/app/apps/portal-server/build/services/shell.js:40:13)\n    at async augmentedImplementations.<computed> [as shell] (/app/node_modules/.pnpm/@ddadaal+tsgrpc-server@0.19.4_@grpc+grpc-js@1.9.5/node_modules/@ddadaal/tsgrpc-server/lib/server.js:76:33)","code":13,"details":"Error when connecting to remote","metadata":{"is_scow_error":["1"],"scow_error_code":["SSH_ERROR"]}},"msg":"Error occurred during response streaming. Emit the error to the stream"}
{"level":30,"time":1699584266546,"pid":18,"hostname":"9fb98df644be","req":"15","path":"/scow.portal.ShellService/Shell","msg":"Ending response stream"}

**Comment by liu-shaobo** [comment]
selinux导致这个问题
