### ISSUE TITLE
交互式应用显示“应用还未准备好”

### ISSUE THREAD

**Issue by yuguoshao** [PKUHPC/SCOW#975]
<img width="1590" alt="image" src="https://github.com/PKUHPC/SCOW/assets/61077538/6b145d33-d079-4fb7-ab89-a5083c2631c6">
交互式应用创建之后一直提示应用还未准备好

sbatch的输出看起来一切正常
```shell
#slurm-81.out

[2023-11-14T03:16:01.992Z] debug parent:52814 spawned child process 52831
[2023-11-14T03:16:02.334Z] debug child:52831 initiating handshake
[2023-11-14T03:16:02.336Z] debug parent:52814 got message [38;2;140;140;140m{"message":{"type":"handshake"}}[0m
[2023-11-14T03:16:02.338Z] debug child:52831 got message [38;2;140;140;140m{"message":{"type":"handshake","args":{"bind-addr":"0.0.0.0:42797","auth":"password","password":"<redacted>","config":"/pacific/home/yuguo/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/pacific/home/yuguo/.local/share/code-server","extensions-dir":"/pacific/home/yuguo/.local/share/code-server/extensions","session-socket":"/pacific/home/yuguo/.local/share/code-server/code-server-ipc.sock","log":"trace","host":"0.0.0.0","port":42797,"proxy-domain":[],"_":[],"usingEnvPassword":true,"usingEnvHashedPassword":false}}}[0m
[2023-11-14T03:16:02.339Z] info  code-server 4.18.0 d7a2b4936af1bfd80cb96f2567af68badc2325e3
[2023-11-14T03:16:02.339Z] info  Using user-data-dir /pacific/home/yuguo/.local/share/code-server
Trace: [2023-11-14T03:16:02.340Z] trace Using extensions-dir /pacific/home/yuguo/.local/share/code-server/extensions
    at doLog (/pacific/software/code-server/4.18.0/node_modules/@coder/logger/out/logger.js:57:28)
    at ServerFormatter.doWrite (/pacific/software/code-server/4.18.0/node_modules/@coder/logger/out/logger.js:200:20)
    at ServerFormatter.write (/pacific/software/code-server/4.18.0/node_modules/@coder/logger/out/logger.js:119:14)
    at Logger.handle (/pacific/software/code-server/4.18.0/node_modules/@coder/logger/out/logger.js:339:25)
    at Logger.trace (/pacific/software/code-server/4.18.0/node_modules/@coder/logger/out/logger.js:268:14)
    at /pacific/software/code-server/4.18.0/out/node/main.js:95:21
    at Generator.next (<anonymous>)
    at /pacific/software/code-server/4.18.0/out/node/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/pacific/software/code-server/4.18.0/out/node/main.js:4:12)
[2023-11-14T03:16:02.355Z] info  Using config file /pacific/home/yuguo/.config/code-server/config.yaml
[2023-11-14T03:16:02.355Z] info  HTTP server listening on http://0.0.0.0:42797/
[2023-11-14T03:16:02.356Z] info    - Authentication is enabled
[2023-11-14T03:16:02.356Z] info      - Using password from $PASSWORD
[2023-11-14T03:16:02.356Z] info    - Not serving HTTPS
[2023-11-14T03:16:02.356Z] info  Session server listening on /pacific/home/yuguo/.local/share/code-server/code-server-ipc.sock
```

**Comment by yuguoshao** [comment]
问题解决，没有配置好scow部署节点的hosts文件
